# Generated by Django 4.2.4 on 2023-08-06 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autherization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='otpExpire',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 6, 12, 13, 35, 642999, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
