# Generated by Django 4.2.4 on 2023-08-06 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autherization', '0002_usermodel_otpexpire_alter_usermodel_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 6, 12, 15, 30, 30413, tzinfo=datetime.timezone.utc)),
        ),
    ]
