# Generated by Django 4.2.4 on 2023-08-06 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('autherization', '0004_alter_usermodel_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
