# Generated by Django 4.2.4 on 2023-08-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autherization', '0005_alter_usermodel_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.BinaryField(max_length=500),
        ),
    ]
